name: Update Draft Tap
on:
  workflow_dispatch:
  pull_request:
    branches: [master]
  schedule:
    - cron: "0 0 * * *"
permissions:
  contents: read

jobs:
  update-tap:
    runs-on: macos-13
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@a4aa98b93cab29d9b1101a6143fb8bce00e2eac4 # v2.7.1
        with:
          egress-policy: audit

      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
      - name: Create New Formula
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          ./create_formula.sh
      - name: upgrade go
        run: |
          brew update
          brew install go
          brew link --overwrite go
      - name: Validate Formula
        run: |
          brew install --build-from-source --verbose ./Formula/draft.rb
      - name: Add & Commit
        if: github.event_name != 'pull_request'
        uses: EndBug/add-and-commit@a94899bca583c204427a224a7af87c02f9b325d5 # v9.1.4
        with:
          message: "Update draft formula"
