name: Update Draft Tap
on:
  workflow_dispatch:
  pull_request:
    branches: [master]
  schedule:
    - cron: "0 0 * * *"
permissions:
  contents: read

jobs:
  update-tap:
    runs-on: macos-13
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f086349bfa2bd1361f7909c78558e816508cdc10 # v2.8.0
        with:
          egress-policy: audit

      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - name: Create New Formula
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          ./create_formula.sh
      - name: upgrade go
        run: |
          brew update
          brew install go
          brew link --overwrite go
      - name: Validate Formula
        run: |
          brew install --build-from-source --verbose ./Formula/draft.rb
      - name: Add & Commit
        if: github.event_name != 'pull_request'
        uses: EndBug/add-and-commit@a94899bca583c204427a224a7af87c02f9b325d5 # v9.1.4
        with:
          message: "Update draft formula"
