name: Update Draft Tap
on:
  workflow_dispatch:
  pull_request:
    branches: [master]
  schedule:
    - cron: "0 0 * * *"
permissions:
  contents: read

jobs:
  update-tap:
    runs-on: macos-13
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit

      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
      - name: Create New Formula
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          ./create_formula.sh
      - name: upgrade go
        run: |
          brew update
          brew install go
          brew link --overwrite go
      - name: Validate Formula
        run: |
          brew install --build-from-source --verbose ./Formula/draft.rb
      - name: Add & Commit
        if: github.event_name != 'pull_request'
        uses: EndBug/add-and-commit@61a88be553afe4206585b31aa72387c64295d08b # v9.1.1
        with:
          message: "Update draft formula"
